### ISSUE TITLE
Enable Nextcloud 23 Support

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/ransomware_protection#109]
Please & Thank you!

**Comment by andyxheli** [comment]
@PVince81 i see that the version has been updated but its not updated on the app store

**Comment by PVince81** [comment]
not sure who's usually uploading these, @skjnldsv do you know ?

**Comment by nickvergessen** [comment]
I do, it's my community app and I will do when I had time to.
There is really no need to ping people in the week of a final release to push for updates.

**Comment by andyxheli** [comment]
@PVince81 thank you for the reply hope you have a nice day!! Much appreciated :)

**Comment by andyxheli** [comment]
> I do, it's my community app and I will do when I had time to.
> 
> There is really no need to ping people in the week of a final release to push for updates.

Thank you so much for taking your time and releasing the update. Your work is very much appreciated without you guys there would not be a Nextcloud. 🙌🏼
