### ISSUE TITLE
User was not blocked when reached 5 blacklisted files in 30 minutes

### ISSUE THREAD

**Issue by pingwiniasty** [nextcloud/ransomware_protection#11]
### Steps to reproduce
1. Make > 5 files with banned extension, eg. test[1-7].8lock8
2. Sync it with application

### Expected behaviour
Blocked user files syncing for some time and in last_strikes UserValue must contains array of 6 files blocked

### Actual behaviour
Only last detected file was added to last_strikes UserValue, the old was not deleted from array

### Server configuration

**Operating system**: Ubuntu 16.04.03
Linux storage 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:** apache 2.4.18-2ubuntu3.4

**Database:** mariadb 10.0.31-0ubuntu0.16.04.2

**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1

**Nextcloud version:**  12.0.2

I made some fix for this. It works on our server

**Comment by nickvergessen** [comment]
Thanks for investigating and providing the fix!

**Comment by nickvergessen** [comment]
I released a new version 1.0.3 with your fix:
https://apps.nextcloud.com/apps/ransomware_protection/releases?platform=12#12

**Comment by pingwiniasty** [comment]
You made my day! I'm very happy to hear this
