### ISSUE TITLE
Menu Item

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/ransomware_protection#112]
a new menu item is displayed in the Personal Menu, in which the only text displayed is the following: Ransomware Protection; Protection is currently active.Please do not create a new menu item but move it to the security section or remove this message completely.

Info:
Nextcloud 23

**Comment by nickvergessen** [comment]
The "additional" section is provided by the server.

We could of course also move it to security, would fit in there.

**Comment by R7JANV1** [comment]
Will it be moved to the security section?

**Comment by nickvergessen** [comment]
If someone sends a patch i can merge it for the next release

**Comment by R7JANV1** [comment]
There is no change in the category for me.

**Comment by R7JANV1** [comment]
can we open this ticket again?

**Comment by nickvergessen** [comment]
It is displayed in `index.php/settings/user/security` now and that is where it should be.
![grafik](https://user-images.githubusercontent.com/213943/221556541-d4534595-dbfd-4da1-847e-056ff387b07d.png)

**Comment by nickvergessen** [comment]
Ah well https://github.com/nextcloud/ransomware_protection/pull/125 was only merged after the 25 release. So will be fixed in the next weeks when I make the app compatible with 26 and then release a new version
