### ISSUE TITLE
too many positive false alarm -- impossible to use

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/ransomware_protection#113]
NC23.0.3 + NC3.4.4 + Ransomware app

TOO MANY POSITIVE FALSE ALERT.

All files like dll, exe, dat, ott, pro ... are simply blocked when synchronizing...

Add to disable the ransomware app  to regain sync. Impossible to use.... had over 487GO to synch, about 67% of the files were blocked !!! Lost around 19hours of sync

Of course, all those block files are mine and known not to be ransomware files...

**Comment by nickvergessen** [comment]
Please see https://github.com/nextcloud/ransomware_protection#configuration-settings

Other than that if all files are yours just remove the app 🤷‍♂️
