### ISSUE TITLE
Cooperate/create bundle with files_antivirus app?

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/ransomware_protection#13]
Hello,

to provide a bit more security, this app could be offered as a bundle with the files_antivirus app. Aside from typical ransomware extensions the detection of known viruses and other malware would be beneficial too.

**Comment by nickvergessen** [comment]
Well there is a huge difference between both apps on the technical side, so merging them is not really a good idea.
Also I'm not sure what the development status of the app is atm.

About creating an app bundle for the two apps: maybe when there are more security focus apps.

**Comment by e-alfred** [comment]
Well, not really merging, but offering an app bundle like the education or the communication bundle that groups them together would be enough I think.

About the activity I can see that the Owncloud repository is more active compared to the Nextcloud repository regarding the files_antivirus app. Maybe merging in the changes from the more actively developed version into the Nextcloud repository would be the way to go?

**Comment by nickvergessen** [comment]
Closing stale issue
