### ISSUE TITLE
Supporting Web interface

### ISSUE THREAD

**Issue by H14m** [nextcloud/ransomware_protection#139]
Hi i found in issue number #80 that 
> Ransomware can not upload via the browser, so that is not blocked intentionally, but only when it comes from the desktop client

i would like to get some hints of how could i implement the browser support

**Comment by nickvergessen** [comment]
What is the usecase of this? Manually uploading via the web interface is nothing ransomware can do.

**Comment by nickvergessen** [comment]
You should be able to achieve this with the https://github.com/nextcloud/files_accesscontrol app already

**Comment by nickvergessen** [comment]
For this app here, it is not planned to extend the functionality to browsers
