### ISSUE TITLE
new extention: new variation discovered by Locky

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/ransomware_protection#15]
Hi, 

since 20.09.2017 is a new variation discovered by Locky.
The file extension is .ykcol - could you please add this extention into  ransomware_protection/resources/extensions.txt

Source: [t3n.de](http://t3n.de/news/locky-trojaner-849280/)

**Comment by nickvergessen** [comment]
Feel free to send a pull request.
If you increase the version in appinfo/info.xml and add it to the changelog, I can release right away

**Comment by mr-bolle** [comment]
I know with the possibilities with github not yet, but will test it once.

**Comment by nickvergessen** [comment]
Fixed in #18

**Comment by nickvergessen** [comment]
Also released 1.0.4:
https://apps.nextcloud.com/apps/ransomware_protection
