### ISSUE TITLE
Additional: detect crypted files

### ISSUE THREAD

**Issue by morph027** [nextcloud/ransomware_protection#2]
First of all, thanks! Great idea, especially in times like these.

I don't know much about Nextcloud plugin development (DevOps guy with heart and soul for the bigger picture ;) ), but i immediatley though that https://github.com/unixist/cryptostalker would fit in here really good.

Quick shot blueprint: As it's a simple binary, we could add it to the Nextcloud instance as a normal system service watching the data directory. As we can trigger actions on detection, we could probably just hook into the plugin from the outside somehow (not sure if this is possible, i just think of the same mechanism like with cronjobs) and display a warning + refuse the upload or whatever action will be appropriate.

**Comment by KevinAT** [comment]
since some (older) crypto malware keys are public already, maybe the app could tell you which crypto malware/encryption key might have been used on your files.

**Comment by nickvergessen** [comment]
I added a console command in #5 

You can now call `./occ ransomware_protection:block <user>` to block a user from further syncing.

You can combine this with:
```
# This will call a script (see contrib/scripts directory) when an encrypted file is seen anywhere under $HOME
$ cryptostalker --path=$HOME --script=/usr/local/bin/alert.sh
```

just call a sh script, which gets the affected user from the path and call the occ script with that name.

**Comment by morph027** [comment]
Uh, cool...Will try this out soon ;)

**Comment by e-alfred** [comment]
Could this be added to the documentation maybe?
