### ISSUE TITLE
Request: add translation file foor transifex

### ISSUE THREAD

**Issue by mjanssens** [nextcloud/ransomware_protection#22]
Hi, I don't see any l10n folder.
Currently Ransomware App is only presented in english and doesn't follow main language of the webpage.
Could you add transifex import please?

**Comment by nickvergessen** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
Voila: https://www.transifex.com/nextcloud/nextcloud/ransomware_protection/

**Comment by mjanssens** [comment]
Merci!

**Comment by leonidasv** [comment]
When will the translations be available on the AppStore release?

**Comment by nickvergessen** [comment]
The next release will come when #30 is fixed.
