### ISSUE TITLE
Sort extensions alphabetically

### ISSUE THREAD

**Issue by dienteperro** [nextcloud/ransomware_protection#29]
### Expected behaviour
The list of extensions (https://github.com/nextcloud/ransomware_protection/blob/master/resources/extensions.txt) IMHO should be sorted alphabetically. This will help in readability and additions for humans.

### Actual behaviour
The list is not sorted.

**Comment by nickvergessen** [comment]
The list was copied from another source and we just appended new extensions at the end.

I don't think ordering them alphabetically has a huge benefit. It's fast to use the search of your browser/editor to find the right place.

**Comment by dienteperro** [comment]
You are right, nevertheless also helps prevent dupes.
