### ISSUE TITLE
Ransomware protection blocks folder which is named something.blockedextension, shows ambigous error message for files in it

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/ransomware_protection#30]
### Steps to reproduce
1. Upload folder something.blockedextension with files in it.

### Expected behaviour
Folder is legitimate, sync should be allowed to proceed.

### Actual behaviour
Ransomware protection blocks folder upload, all files/folders in it are refused to sync with this error message:

`Not allowed because you don't have permission to add parent folder`

### Server configuration

**Operating system**: Debian 9 Jessie

**Web server:** Apache 2.4

**Database:** Mariadb 10

**PHP version:** PHP 7

**Nextcloud version:** (see Nextcloud admin page) Nextcloud 13.0.2

**Where did you install Nextcloud from:** Official zip file

**Comment by nickvergessen** [comment]
Which folder name was causing troubles for you?

**Comment by nickvergessen** [comment]
Can you check if https://github.com/nextcloud/ransomware_protection/pull/31/files works?
