### ISSUE TITLE
Nextcloud 14 compatibility

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/ransomware_protection#33]
Hey, @nickvergessen, @MorrisJobke and other developers!

Is this app ready for Nextcloud 14? Did anybody test this?

Ref https://github.com/orgs/nextcloud/projects/15#card-11847070.

**Comment by nickvergessen** [comment]
Nextcloud 14 will be released on monday, I will make sure that a release is available in time

**Comment by jurgenhaas** [comment]
Thanks for your feedback. Just to let you know, Nextcloud 14 got released this morning, see https://github.com/nextcloud/server/releases/tag/v14.0.0

**Comment by nickvergessen** [comment]
I'm fully aware of the git tag, because I'm one of 2 persons in charge of creating it ;)
But the full release is scheduled for monday

**Comment by nickvergessen** [comment]
Published and also added GandCrab for 13+14
