### ISSUE TITLE
Blocking mp3?

### ISSUE THREAD

**Issue by brantje** [nextcloud/ransomware_protection#4]
https://github.com/nextcloud/ransomware_protection/blob/c7ead07bc0921d2b149cd80e9522db288fba0ff2/resources/extensions.txt#L319

Just saw this, not sure if we should block `.mp3`.
I have a lot of music, and this if i would enable this app, it would prevent me to upload mp3's to Nextcloud.

**Comment by nickvergessen** [comment]
Yeah I will check the list again.

**Comment by e-alfred** [comment]
Is blocking generic *.exe files a good idea too? I mean, distributing legitimate *.exe files using Nextcloud is quite useful, at least in selected folders only editable by trusted users.

**Comment by brantje** [comment]
Don't know if it's possible to check if the exe as a digital signature?

**Comment by e-alfred** [comment]
Same goes for *.dll files...

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/ransomware_protection/pull/5/files#diff-cbc670d7466fc5e5f50fb91f671d6cd4

This is what i changed so far
