### ISSUE TITLE
Ransomware protection seems to be blocking all instances of yarn.lock

### ISSUE THREAD

**Issue by jcklpe** [nextcloud/ransomware_protection#40]
### Steps to reproduce
1. store npm modules in project in a folder synced by nextcloud
2. open up web portal and see notification saying ransomeware had blocked yarn.lock files for fitting the name of a known ransomware threat
3.

### Expected behaviour
IDK but it seems like yarn.lock is just a common file for projects that use the yarn package manager so that shouldn't be an issue right?

**Operating system**:
Ubuntu 18
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
14.03

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 10

I didn't fill everything out because they seem to have nothing to do with the actual issue. Is there a ransomware protection specific log I could get ya''ll though?

**Comment by nickvergessen** [comment]
Yeah, one of the ransomwares renames all files to `.lock`:
https://github.com/nextcloud/ransomware_protection/blob/master/resources/extensions.txt#L35

But you can add `.loc` to the excluded pattern if you want to allow it.
