### ISSUE TITLE
Storage wrapper 'ransomware_protection' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/ransomware_protection#46]
I have a lot of the following messages in my Nextcloud log:
```
Storage wrapper 'ransomware_protection' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.
```

Nextcloud: 15.0.4.0
Installierte Apps: 94
PHP: 7.2.15
Datenbank: mysql

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/ransomware_protection/blob/master/lib/AppInfo/Application.php#L44

![Well yes, but actually no](https://i.kym-cdn.com/entries/icons/original/000/028/596/dsmGaKWMeHXe9QuJtq_ys30PNfTGnMsRuHuo_MUzGCg.jpg)

Im confused

**Comment by Wotisrv** [comment]
Hei,
I changed my harddisk today because of defect sectors. I'm on version 15.0.5 and there was no errors in Nextcloud log file. After changing to new harddisk and copying over meg backup files I get permantly the following error message as in the topic:
Storage wrapper 'ransomware_protection' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems. 
This is what i tried:
Deletet and reinstalled the regarding app. Checked for errors via occ. Reinstalled both client app and mobile app. Nothing helped.

@nichtvergessen: What did your picture mean? I'm confused too

Best regards
Tino Wolf

**Comment by DigitDaniel** [comment]
Hi guys,

I have same issue in my logs.

If I execute the occ command "app:check-code ransomware_protection" I get following answer:

apps/ransomware_protection/lib/AppInfo/Application.php
 2 errors
    line   45: OCP\App - Static method of deprecated class must not be called
    line   45: OCP\App::registerPersonal - Method of deprecated class must not be called
App is not compliant

**Comment by Wotisrv** [comment]
Hello again,

I get the same errors as DigitDaniel wrote.

**Comment by nickvergessen** [comment]
Those deprecation messages are unrelated and not a problem.

**Comment by Wotisrv** [comment]
yeah but if activated I get plenty of those error messages:

{"reqId":"XLePxTGD7mkMHDiDwespRAAAANI","level":2,"time":"2019-04-17T22:42:45+02:00","remoteAddr":"13.125.9.175","user":"--","app":"filesystem","method":"GET","url":"/index.php/login","message":"Storage wrapper 'ransomware_protection' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0","version":"15.0.7.0","id":"5cb78fc6a2c27"}

[filesystem] Warning: Storage wrapper 'ransomware_protection' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.

GET /index.php/login
from 13.125.9.175 at 2019-04-17T22:42:45+02:00

**Comment by nickvergessen** [comment]
level 2 means "warning" not error.

I still couldnt find out what is causing this, as I can not reproduce the issue locally. and as you can see in https://github.com/nextcloud/ransomware_protection/blob/master/lib/AppInfo/Application.php#L44 we use that event to register the wrapper.

**Comment by jonathanmmm** [comment]
Having the same warning every few minutes.

Debian stretch
Nextcloud 15.0.7
MariaDB
Php 7.3
Redis (as locking)
Apcu (as cache)

May be the error was not there when I was still using php7.0 I could switch back and see if it works that way if you want?!

**Comment by jonathanmmm** [comment]
Is this warning important? What should ne fixed? And if nothing is there a way that this warning does not bombard the logs? That way I have to disable warnings and if there is an important warning I won't see it.

**Comment by Wotisrv** [comment]
I don't remember when the warning getting started. But there was a time before without those warnings.
It came with an update suddenly, I guess.
Fedora 29 Server Edition
Nextcloud 15.0.7
MariaDB 10.3.12
Php 7.2.17
Redis No
Apcu Yes

Got the instructions from www.c-rieger.de too :)

**Comment by nickvergessen** [comment]
Can one of you try to help me?

Open `lib/private/Files/Filesystem.php`:
find:
```php
			\OC::$server->getLogger()->warning("Storage wrapper '{wrapper}' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.", [
```
before add:
```php
			\OC::$server->getLogger()->logException(new \Exception('Help nickvergessen'), [
				'message' => 'Help nickvergessen',
				'app' => 'nickvergessen',
			]);
```

then check the log after some time if there is an entry to app `nickvergessen` and send the log to me or post it here.

**Comment by Wotisrv** [comment]
I did as you wrote and here are the entries of the log right after I startet up NC client app.
`{"reqId":"XNCL2unoE80klADIOT5CqwAAAJY","level":3,"time":"2019-05-06T21:32:42+02:00","remoteAddr":"85.166.192.87","user":"--","app":"nickvergessen","method":"PROPFIND","url":"/nextcloud/remote.php/webdav/","message":{"Exception":"Exception","Message":"Help nickvergessen","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/ransomware_protection/lib/AppInfo/Application.php","line":54,"function":"addStorageWrapper","class":"OC\\Files\\Filesystem","type":"::","args":["ransomware_protection",[{"__class__":"OCA\\RansomwareProtection\\AppInfo\\Application"},"addStorageWrapperCallback"],-10]},{"file":"/var/www/html/nextcloud/lib/private/legacy/hook.php","line":106,"function":"addStorageWrapper","class":"OCA\\RansomwareProtection\\AppInfo\\Application","type":"->","args":[{"user":""}]},{"file":"/var/www/html/nextcloud/lib/private/legacy/util.php","line":281,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","preSetup",{"user":""}]},{"file":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":128,"function":"setupFS","class":"OC_Util","type":"::","args":[]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php","line":105,"function":"validateUserPass","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":253,"function":"check","class":"Sabre\\DAV\\Auth\\Backend\\AbstractBasic","type":"->","args":[{"absoluteUrl":"https://woti.dedyn.io/nextcloud/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":155,"function":"auth","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":[{"absoluteUrl":"https://woti.dedyn.io/nextcloud/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":201,"function":"check","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":[{"absoluteUrl":"https://woti.dedyn.io/nextcloud/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":150,"function":"check","class":"Sabre\\DAV\\Auth\\Plugin","type":"->","args":[{"absoluteUrl":"https://woti.dedyn.io/nextcloud/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->","args":[{"absoluteUrl":"https://woti.dedyn.io/nextcloud/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"autoRequireLogin":true,"__class__":"Sabre\\DAV\\Auth\\Plugin"},"beforeMethod"],[{"absoluteUrl":"https://woti.dedyn.io/nextcloud/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",[{"absoluteUrl":"https://woti.dedyn.io/nextcloud/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://woti.dedyn.io/nextcloud/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/nextcloud/remote.php","line":163,"args":["/var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/lib/private/Files/Filesystem.php","Line":234,"CustomMessage":"Help nickvergessen"},"userAgent":"Mozilla/5.0 (Windows) mirall/2.5.1final (build 20181204) (Nextcloud)","version":"15.0.7.0","id":"5cd08be8a9f69"}`

and

> [nickvergessen] Error: Exception: Help nickvergessen at <<closure>>

 0. /var/www/html/nextcloud/apps/ransomware_protection/lib/AppInfo/Application.php line 54
    addStorageWrapper("ransomware_protection", [OCA\RansomwareP ... "], -10)
 1. /var/www/html/nextcloud/lib/private/legacy/hook.php line 106
    addStorageWrapper({user: ""})
 2. /var/www/html/nextcloud/lib/private/legacy/util.php line 281
    emit("OC_Filesystem", "preSetup", {user: ""})
 3. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php line 128
    setupFS()
 4. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php line 105
    validateUserPass("*** sensitive parameters replaced ***")
 5. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php line 253
    check(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 6. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php line 155
    auth(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php line 201
    check(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 8. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php line 150
    check(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 9. <<closure>>
    beforeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
10. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\Auth\ ... "], [Sabre\HTTP\Requ ... }])
11. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 466
    emit("beforeMethod", [Sabre\HTTP\Requ ... }])
12. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
13. /var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
    exec()
14. /var/www/html/nextcloud/remote.php line 163
    require_once("/var/www/html/n ... p")

PROPFIND /nextcloud/remote.php/webdav/
from 85.166.192.87 at 2019-05-06T21:32:42+02:00

**Comment by Schmuuu** [comment]
Hello,

These messages just started to appear in my nextcloud logs as well. I actually wanted to open a case in the ransomware_detection repository, because these logs appeared right after enabling "Ransomware Detection" today after it received the update to support NC16.
I then found this issue there:
https://github.com/undo-ransomware/ransomware_detection/issues/9
and came here.

For a test, I disabled "Ransomware Detection" again. The messages didn't come up again. Shortly after I re-enabled the app, the messages returned.

@nickvergessen I don't understand app development. Do you think this could actually be caused by the other app "Ransomware Detection", although the warning message mentions this app here? Can both apps influence each other in some way, so that "Ransomware Detection" causes an issue for this app here?

I hope some of my babbling makes any sense and helps.

**Comment by nickvergessen** [comment]
I just tried it and enabled both apps, but no log message appeared. :thinking: 

Open `lib/private/Files/Filesystem.php`:
find:
```php
$previousValue = self::$logWarningWhenAddingStorageWrapper;
```
before add:
```php
			\OC::$server->getLogger()->logException(new \Exception('Also help nickvergessen'), [
				'message' => 'Also help nickvergessen',
				'app' => 'nickvergessen',
			]);
```

But since this is called 4+ times pr page call, just do it quickly and revert it afterwards again

**Comment by Schmuuu** [comment]
Wow, that was a log flooding :D 

```
[nickvergessen] Error: Exception: Also help nickvergessen at <<closure>>

0. /var/www/nextcloud/lib/private/legacy/util.php line 282
   OC\Files\Filesystem::logWarningWhenAddingStorageWrapper(true)
1. /var/www/nextcloud/lib/base.php line 974
   OC_Util::setupFS()
2. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /apps/logreader/poll?lastReqId=Rf****gR
from [IP-removed] by [USERNAME-removed] at 2019-05-14T11:20:54+02:00
```
I hope this output helps.

**Comment by Wotisrv** [comment]
I haven't reverted it yet in the case you'll need some more info :) I have to deactivate the addon otherwise it will full up the log file just with warning messages. The warning messages appear as soon the addon is getting activated.

What kind of system do you use @nickvergessen ?

**Comment by nickvergessen** [comment]
@Schmuuu mind to send the log file my way? `<github name>@nextcloud.com`
There should be a lot different stacktraces and the order of that and the other debug log entry is important to know :)

Maybe you can try to access your file system and send me all logs for one request-id

**Comment by Schmuuu** [comment]
@nickvergessen Okay, sent it to you. Let me know if you need something else. I'm happy to help out.

**Comment by nickvergessen** [comment]
Okay, finally found out the problem.

So it's a result of 3 combined apps:
1. Group folders
2. Ransomware detection
3. Ransomware protection

The actual problem is, that the group folder app sets up the filesystem a second time.

```json
{
  "reqId": "wdo8GxcOdOa6wJAp7lor",
  "level": 3,
  "time": "2019-05-14T14:01:48+02:00",
  "remoteAddr": "178.21.23.139",
  "user": "--",
  "app": "nickvergessen",
  "method": "POST",
  "url": "\/index.php\/apps\/files_sharing\/shareinfo?t=....",
  "message": {
    "Exception": "Exception",
    "Message": "Also help nickvergessen",
    "Code": 0,
    "Trace": [
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/legacy\/util.php",
        "line": 282,
        "function": "logWarningWhenAddingStorageWrapper",
        "class": "OC\\Files\\Filesystem",
        "type": "::",
        "args": [
          true
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Mount\/Manager.php",
        "line": 122,
        "function": "setupFS",
        "class": "OC_Util",
        "type": "::",
        "args": [
          
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/View.php",
        "line": 1397,
        "function": "findIn",
        "class": "OC\\Files\\Mount\\Manager",
        "type": "->",
        "args": [
          "\/__groupfolders"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/Root.php",
        "line": 198,
        "function": "getFileInfo",
        "class": "OC\\Files\\View",
        "type": "->",
        "args": [
          "\/__groupfolders"
        ]
      },
      {
        "function": "get",
        "class": "OC\\Files\\Node\\Root",
        "type": "->",
        "args": [
          "\/__groupfolders"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/LazyRoot.php",
        "line": 64,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "__class__": "OC\\Files\\Node\\Root"
            },
            "get"
          ],
          [
            "__groupfolders"
          ]
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/LazyRoot.php",
        "line": 141,
        "function": "__call",
        "class": "OC\\Files\\Node\\LazyRoot",
        "type": "->",
        "args": [
          "get",
          [
            "__groupfolders"
          ]
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/AppInfo\/Application.php",
        "line": 53,
        "function": "get",
        "class": "OC\\Files\\Node\\LazyRoot",
        "type": "->",
        "args": [
          "__groupfolders"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php",
        "line": 118,
        "function": "OCA\\GroupFolders\\AppInfo\\{closure}",
        "class": "OCA\\GroupFolders\\AppInfo\\Application",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
        "line": 117,
        "function": "offsetGet",
        "class": "Pimple\\Container",
        "type": "->",
        "args": [
          "GroupAppFolder"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
        "line": 401,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "GroupAppFolder"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
        "line": 379,
        "function": "queryNoFallback",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->",
        "args": [
          "GroupAppFolder"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/AppInfo\/Application.php",
        "line": 77,
        "function": "query",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->",
        "args": [
          "GroupAppFolder"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php",
        "line": 118,
        "function": "OCA\\GroupFolders\\AppInfo\\{closure}",
        "class": "OCA\\GroupFolders\\AppInfo\\Application",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
        "line": 117,
        "function": "offsetGet",
        "class": "Pimple\\Container",
        "type": "->",
        "args": [
          "OCA\\GroupFolders\\Trash\\TrashBackend"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
        "line": 401,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "OCA\\GroupFolders\\Trash\\TrashBackend"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/ServerContainer.php",
        "line": 134,
        "function": "queryNoFallback",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->",
        "args": [
          "OCA\\GroupFolders\\Trash\\TrashBackend"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/apps\/files_trashbin\/lib\/AppInfo\/Application.php",
        "line": 91,
        "function": "query",
        "class": "OC\\ServerContainer",
        "type": "->",
        "args": [
          "OCA\\GroupFolders\\Trash\\TrashBackend"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/apps\/files_trashbin\/lib\/AppInfo\/Application.php",
        "line": 73,
        "function": "registerTrashBackends",
        "class": "OCA\\Files_Trashbin\\AppInfo\\Application",
        "type": "->",
        "args": [
          
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/ServerContainer.php",
        "line": 103,
        "function": "__construct",
        "class": "OCA\\Files_Trashbin\\AppInfo\\Application",
        "type": "->",
        "args": [
          
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/ServerContainer.php",
        "line": 133,
        "function": "getAppContainer",
        "class": "OC\\ServerContainer",
        "type": "->",
        "args": [
          "files_trashbin",
          "Files_Trashbin"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/apps\/files_trashbin\/lib\/Storage.php",
        "line": 201,
        "function": "query",
        "class": "OC\\ServerContainer",
        "type": "->",
        "args": [
          "OCA\\Files_Trashbin\\Trash\\ITrashManager"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/StorageFactory.php",
        "line": 101,
        "function": "OCA\\Files_Trashbin\\{closure}",
        "class": "OCA\\Files_Trashbin\\Storage",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Mount\/MountPoint.php",
        "line": 148,
        "function": "wrap",
        "class": "OC\\Files\\Storage\\StorageFactory",
        "type": "->",
        "args": [
          "*** sensitive parameter replaced ***",
          "*** sensitive parameter replaced ***"
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Mount\/MountPoint.php",
        "line": 172,
        "function": "createStorage",
        "class": "OC\\Files\\Mount\\MountPoint",
        "type": "->",
        "args": [
          
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Mount\/MountPoint.php",
        "line": 236,
        "function": "getStorage",
        "class": "OC\\Files\\Mount\\MountPoint",
        "type": "->",
        "args": [
          
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/StorageFactory.php",
        "line": 56,
        "function": "wrapStorage",
        "class": "OC\\Files\\Mount\\MountPoint",
        "type": "->",
        "args": [
          [
            {
              "__class__": "OCA\\RansomwareDetection\\AppInfo\\Application"
            },
            "addStorageWrapperCallback"
          ]
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php",
        "line": 245,
        "function": "addStorageWrapper",
        "class": "OC\\Files\\Storage\\StorageFactory",
        "type": "->",
        "args": [
          "ransomware_detection",
          [
            {
              "__class__": "OCA\\RansomwareDetection\\AppInfo\\Application"
            },
            "addStorageWrapperCallback"
          ],
          -10,
          {
            "\/": "*** sensitive parameter replaced ***"
          }
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/apps\/ransomware_detection\/lib\/AppInfo\/Application.php",
        "line": 148,
        "function": "addStorageWrapper",
        "class": "OC\\Files\\Filesystem",
        "type": "::",
        "args": [
          "ransomware_detection",
          [
            {
              "__class__": "OCA\\RansomwareDetection\\AppInfo\\Application"
            },
            "addStorageWrapperCallback"
          ],
          -10
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/legacy\/hook.php",
        "line": 106,
        "function": "addStorageWrapper",
        "class": "OCA\\RansomwareDetection\\AppInfo\\Application",
        "type": "->",
        "args": [
          {
            "user": ""
          }
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/legacy\/util.php",
        "line": 281,
        "function": "emit",
        "class": "OC_Hook",
        "type": "::",
        "args": [
          "OC_Filesystem",
          "preSetup",
          {
            "user": ""
          }
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/lib\/base.php",
        "line": 974,
        "function": "setupFS",
        "class": "OC_Util",
        "type": "::",
        "args": [
          
        ]
      },
      {
        "file": "\/var\/www\/nextcloud\/index.php",
        "line": 42,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": [
          
        ]
      }
    ],
    "File": "\/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php",
    "Line": 222,
    "CustomMessage": "Also help nickvergessen"
  },
  "userAgent": "GuzzleHttp\/6.3.3 curl\/7.52.1 PHP\/7.3.5-1+0~20190503093827.38+stretch~1.gbp60a41b",
  "version": "16.0.0.9"
}
```

In this stacktrace, step 2:
```json
      {
        "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Mount\/Manager.php",
        "line": 122,
        "function": "setupFS",
        "class": "OC_Util",
        "type": "::",
        "args": [
          
        ]
      }
```
is the same as the second last:
```json
      {
        "file": "\/var\/www\/nextcloud\/lib\/base.php",
        "line": 974,
        "function": "setupFS",
        "class": "OC_Util",
        "type": "::",
        "args": [
          
        ]
      }
```
that method always forces the logging to true. but since it is nested, it shouldn't do that on the first exist, but only on the most outer one. Now that could easily be fixed, the question is whether calling a nested setupFS is actually what should happen at all.
I will check with the experts.

**Comment by jurgenhaas** [comment]
Happy to see that you've found the cause of the issue. Just wanted to let you know that this could get potentially critical as e.g. my own relatively small installation got up to 23GB of log files with almost all of the entries have been of that nature.

**Comment by Wotisrv** [comment]
Why is it closed? Is the issue fixed?

**Comment by nickvergessen** [comment]
Yes, it will be fixed with the next update of the Nextcloud server package

**Comment by Wotisrv** [comment]
Ah, alright. Because I tested this morning and the messages are still displayed. 
Thanks for the efforts :)

**Comment by mydogspies** [comment]
Sorry to re-open a can of worms but still having exactly the same problem on a fresh install of version 21.0.1.
