### ISSUE TITLE
.aac extension is also a valid audio file

### ISSUE THREAD

**Issue by rklasen** [nextcloud/ransomware_protection#55]
### Steps to reproduce
1. upload any .aac file
2. ransomware protection kicks in

### Expected behaviour
Ideally, scan if the file is really an audio file (magic byte for example).

### Actual behaviour
Android app informs about possible infection and offers to pause protection.

### Server configuration

**Operating system**:
Debian

**Web server:**
apache

**Database:**
mysql

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
16.0

**Where did you install Nextcloud from:**
official docker image

**Signing status:**
Signed

```
No errors have been found.
```

**List of activated apps:**

Unsure, ransomware protection.

**Nextcloud configuration:**

```
unsure, not applicaple
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
Sure thing. If you need it and use it, just add it to the exclude list in the admin settings.
