### ISSUE TITLE
Clarify app description

### ISSUE THREAD

**Issue by s-hemer** [nextcloud/ransomware_protection#57]
Maybe you could extend the app description (and README) to clarify that this extension covers uploads from the client as well. I had to read through the issues because I was unsure after looking at the screenshot. Would make no sense otherwise of course but somehow, I was confused (and people not having a look through Github issues might also be).
And of course, this does also not free you from doing regular backups.

Regards

Steffen

**Comment by nickvergessen** [comment]
The first sentence of the readme is:
> This app prevents uploading files with known ransomware file endings.

Same for the app description. It actually only covers uploads from clients, as manual uploads are not how todays ransomware attacks work. Should we change it to:

> This app prevents the Nextcloud clients from uploading files with known ransomware file endings.

**Comment by s-hemer** [comment]
You are absolutely right, it would not make sense to prevent manual uploads. I somehow didn't see that at the first place and was confused by the screenshot which only shows the resulting notification in the webinterface. 
Your suggestion sound good. The question would be if a note for regular backups (additionally to the no guarantee statement) makes sense and a short description (like on the README) how the user in case are informed (webinterface announcement, client notification?, mail?)

**Comment by nickvergessen** [comment]
Feel free to check https://github.com/nextcloud/ransomware_protection/pull/58

**Comment by sudwhiwdh** [comment]
Does "Nextcloud Sync clients" include the use of the web interface as well? Or actually only uploads via the desktop and mobile apps.

**Comment by nickvergessen** [comment]
Only clients not your browser. Your browser can not automatically download-encrypt-reupload the files...

**Comment by sudwhiwdh** [comment]
Thank you! Is it not technically possible to also check when manually uploading files to the web interface?

**Comment by nickvergessen** [comment]
It makes no sense. Ransomware attacks can't happen via the web interface
