### ISSUE TITLE
Nextcloud 18 - doesn't seem to prevent anything

### ISSUE THREAD

**Issue by ngoonee** [nextcloud/ransomware_protection#62]
### Steps to reproduce
1. Download and Enable this app
2. Touch a file (test.enc)
3. Rename existing file to add .enc extension

### Expected behaviour
Both should be prevented and logged in user should get notification

### Actual behaviour
Nothing as far as I can tell. Files just upload successfully.

### Server configuration
**Operating system**:
Arch Linux x86_64. Am running the nextcloud official docker image, so Apache webserver with a separate docker image for postgres database. Migrated over from previous install from Arch Linux repos. Nextcloud 18.0.0

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.
```

**List of activated apps:**
The defaults, plus ransomware protection

```Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_protection: 1.6.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - user_ldap

```

**Nextcloud configuration:**

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.myurl.duckdns.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "18.0.0.10",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/nextcloud.myurl.duckdns.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "filelocking.enabled": false,
        "theme": "",
        "loglevel": 2
    }
}
```

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Operating system:**

Arch Linux 64-bit (different machine)

#### Nextcloud log (data/owncloud.log)
```
No related logs (just messages about maintenance mode when I enable/disable it and Memcache unavailable reminders).
```

#### Browser log
```
Not related to browser.
```

**Comment by g-work** [comment]
I changed the file extension of a png to enc and the Nextcloud client gave me an error and didn't upload the changed file to the server. Also I got a message in the web interface. But in explorer, it showed up as successfully synced (green symbol).

**Comment by nickvergessen** [comment]
Works pretty fine here. After I rename a file, the blue "sync" icon appears and afterwards the green checkmark is gone.

**Comment by acs-ferreira** [comment]
@nickvergessen i've tested here by uploading trough the browser, file is uploaded:

- `occ app:enable ransomware_protection`
- rename a `.jpg` to `.jpg.enc`
- upload trough the browser

Object Storage as primary. NC 17 or 18.

![image](https://user-images.githubusercontent.com/12234510/75987156-bb40c400-5eef-11ea-9587-8b37f6831772.png)

**Comment by nickvergessen** [comment]
Yes, please see the readme. Browser upload is not happening when your computer is infected by ransomware, so of course it is nit blocked

**Comment by tortuetorche** [comment]
Hi,

I can replicate this issue reported by @ngoonee, if the [Group folders](https://apps.nextcloud.com/apps/groupfolders) application is enabled.

I tested this bug on multiple installations (production, staging, dev) and multiple Desktop clients (Windows, Linux).
And no need to do specific configuration on the `groupfolders` application, if it's enabled, the `ransomware_protection` application doesn't prevent anything :fearful: 

Can you check this @nickvergessen, please?

Reference: #50

Have a good day,
Tortue Torche

**Comment by tortuetorche** [comment]
Hi folks,

Here some news, this issue occurs only if the [`files_versions`](https://github.com/nextcloud/server/tree/v18.0.2/apps/files_versions)(Versions) application is enabled, and obviously the `groupfolders` application, see my [previous comment](https://github.com/nextcloud/ransomware_protection/issues/62#issuecomment-604316957).

So you can disable the `files_versions` application, to reactive the ransomware protection, but it's a huge trade-off!

And here a workaround, you can disable the versioning for the files of your group folders, in removing/commenting these lines: https://github.com/nextcloud/groupfolders/blob/v6.0.3/appinfo/info.xml#L67-L69
Of course it's also a big trade-off, because you don't have anymore a shared versioning with others users in your group folders, but I only found this solution for the moment...

Can someone give us some help, please?
Maybe it's a [Group folder](https://github.com/nextcloud/groupfolders) issue, isn't it?

Cheers,
Tortue Torche
