### ISSUE TITLE
Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden. App not found in any app directory

### ISSUE THREAD

**Issue by TBuschmans** [nextcloud/ransomware_protection#67]
### Steps to reproduce
1. Upgrade from php 7.1 to php 7.4 and NC 16.0.4 to 18.0.3
2. All Apps-Checks passed successfully, upgrade passed successfully. NC works fine. 
3. Adding new apps or updating (Ransomeware Protection App) do not work. 

### Expected behaviour
Tell us what should happen
Should update and / or install apps in NC from the NC-App Store.

### Actual behaviour
Tell us what happens instead
After time our is reached ~ 5 seconds NC generates an error message:
"Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.
App not found in any app directory"

Manual apps installation are doing fine. 

### Server configuration

**Operating system**:
Centos 7

**Web server:**
Apache 2.4

**Database:**
mariadb 15.5

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
18.0.03 (same error in 18.0.2)

**Where did you install Nextcloud from:**
Nextcloud.com 

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - admin_notifications: 1.0.2
  - analytics: 2.1.1
  - announcementcenter: 3.7.0
  - audioplayer: 2.9.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - cms_pico: 1.0.5
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - maps: 0.1.6
  - music: 0.13.1
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - occweb: 0.0.7
  - ocr: 6.0.25
  - passman: 2.3.5
  - password_policy: 1.8.0
  - phonetrack: 0.6.2
  - photos: 1.0.0
  - previewgenerator: 2.2.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - ransomware_protection: 1.6.0
  - recommendations: 0.6.0
  - registration: 0.4.7
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_email: 2.0.0
  - spreed: 8.0.5
  - survey_client: 1.6.0
  - terms_of_service: 1.4.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - unsplash: 1.1.5
  - updatenotification: 1.8.0
  - user_usage_report: 1.2.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - accessibility
  - documentserver_community
  - encryption
  - files_external
  - files_rightclick
  - firstrunwizard
  - onlyoffice
  - support
  - systemtags
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ""***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "https:\/\/"***REMOVED SENSITIVE VALUE***"",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "logfile": "\/var\/log\/nextcloud.log",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "maintenance": false,
        "app_install_overwrite": [
            "admin_notifications",
            "activitylog",
            "occweb"
        ],
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\Movie",
            "OC\\Preview\\TXT"
        ],
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379"
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mysql.utf8mb4": true
    }
}


or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Same behavior on Chrome, Firefox and Cliqs
#### Nextcloud log (data/owncloud.log)
{"reqId":"Xnu-TuRxSBXib7S3zLmQmQAAABE","level":3,"time":"2020-03-25T20:30:13+00:00","remoteAddr":"217.6.172.45","user":"tbuschmans","app":"settings","method":"POST","url":"/index.php/settings/apps/enable","message":{"Exception":"Exception","Message":"App not found in any app directory","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":443,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/Installer.php","Line":110,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","version":"18.0.3.0","id":"5e7bc1cb89f77"}
{"reqId":"Xnu-TuRxSBXib7S3zLmQmQAAABE","level":3,"time":"2020-03-25T20:30:13+00:00","remoteAddr":"217.6.172.45","user":"tbuschmans","app":"PHP","method":"POST","url":"/index.php/settings/apps/enable","message":"copy(/var/www/html/nextcloud/apps/external/external/templates/settings.php): failed to open stream: No such file or directory at /var/www/html/nextcloud/lib/private/legacy/helper.php#148","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","version":"18.0.3.0","id":"5e7bc1cb89f8d"}
{"reqId":"Xnu-TuRxSBXib7S3zLmQmQAAABE","level":3,"time":"2020-03-25T20:30:13+00:00","remoteAddr":"217.6.172.45","user":"tbuschmans","app":"PHP","method":"POST","url":"/index.php/settings/apps/enable","message":"mkdir(): No such file or directory at /var/www/html/nextcloud/lib/private/legacy/helper.php#139","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","version":"18.0.3.0","id":"5e7bc1cb89fbf"}
{"reqId":"Xnu-TuRxSBXib7S3zLmQmQAAABE","level":3,"time":"2020-03-25T20:30:13+00:00","remoteAddr":"217.6.172.45","user":"tbuschmans","app":"PHP","method":"POST","url":"/index.php/settings/apps/enable","message":"copy(/var/www/html/nextcloud/apps/external/external/lib/Migration/CopyDefaultIcons.php): failed to open stream: No such file or directory at /var/www/html/nextcloud/lib/private/legacy/helper.php#148","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","version":"18.0.3.0","id":"5e7bc1cb8a02a"}
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
Help very much apreciated.
Thanks

**Comment by nickvergessen** [comment]
I assume that download from the appstore failed because our servers are busy hadning out the 18.0.3 release.
