### ISSUE TITLE
False-positive: hashes in file names (e.g. created by Lollypop)

### ISSUE THREAD

**Issue by rugk** [nextcloud/ransomware_protection#70]
### Steps to reproduce
1. Install the music player [Lollypop](https://wiki.gnome.org/Apps/Lollypop) and use it.
2. Try to sync it's data dir in Nextcloud.
3. E.g. it names artist images and lyrics txt files by some (SHA-256??) hash as a file name. (content is either an image or well… a lyrics text, so absolutely begin)

### Expected behaviour
This triggers this plugin.

-> blocks upload, deletes files

### Actual behaviour
Should not trigger. Should not detect these as randomware.

**Comment by nickvergessen** [comment]
can you give me file names for this?

**Comment by rugk** [comment]
Here are some https://gist.github.com/rugk/0a9e0eea33745bca633dc7c2e9a220d0

**Comment by nickvergessen** [comment]
In the admin settings in the bottom right **Exclude note file pattern** please add:
```
^([a-fA-F0-9]{32})\.txt$
```

**Comment by rugk** [comment]
Well… but this is no solution. IMHO this false-positive should be fixed in the app itself, so it does not reappear.

**Comment by nickvergessen** [comment]
Well the setting is persistent for your instance. the file name matches a ransomware note file, so no we are not going to remove it.
If you don't care about those files the exclude is the way to go.
