### ISSUE TITLE
Some known extensions are missing

### ISSUE THREAD

**Issue by acsfer** [nextcloud/ransomware_protection#73]
Please see https://avepointcdn.azureedge.net/assets/webhelp/compliance_guardian_installation_and_administration/index.htm#!Documents/ransomwareencryptedfileextensionlist.htm

**Comment by nickvergessen** [comment]
It's a bit hard to keep this list updated alone.

I commited my build things on https://github.com/nextcloud/ransomware_protection/pull/74 and I use https://docs.google.com/spreadsheets/d/1TWS238xacAto-fLKh1n5uTsdijWdCEsGIM0Y0Hvmc5g/pubhtml to generate it.

Can you point out what's missing and how I could easily get a programmatic list from that link?

**Comment by kroerig** [comment]
please add .coos to the list of know extension.

**Comment by nickvergessen** [comment]
Ref https://malwarefixes.com/coos-ransomware/

**Comment by DHentzschel** [comment]
@nickvergessen The html table could be parsed from the GET response (URL mentioned by @acsfer); after that, the first column would be added to the extension list.

Example for table to csv conversion:
https://www.convertcsv.com/html-table-to-csv.htm
