### ISSUE TITLE
RouteNotFound exception

### ISSUE THREAD

**Issue by b-pfl** [nextcloud/ransomware_protection#75]
Since a while, I can observe the log file being flooded with the info messages about a RouteNotFound exception:

"Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "ransomwaredetection.page.index" as such route does not exist."

### Steps to reproduce
1. (Maybe) Use an existing Nextcloud installation (upgraded to NC19 or NC20 over mulitple generations, starting from Owncloud 9)
2. Install and activate the ransomware_protection add-on
3. Use Nextcloud & observe log file

### Expected behaviour
NC works without issues and without throwing multiple exceptions.

### Actual behaviour
Exceptions such as the one below are frequently observed:

### Server configuration

**Operating system**: Ubuntu 16.04.

**Web server:** Apache (fpm-fcgi) 

**Database:** MySql 5.7.32

**PHP version:** 7.4.13

**Nextcloud version:** 19.0.6 and 20.0.4

**Where did you install Nextcloud from:** ??? Web, originally from old OwnCloud installation

**Signing status:** ??

No errors have been found

**List of activated apps:**

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - announcementcenter: 4.0.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - checksum: 1.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - cookbook: 0.7.7
  - cospend: 1.2.7
  - dav: 1.16.2
  - deck: 1.2.2
  - documentserver_community: 0.1.8
  - external: 3.7.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.0.4
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - photos: 1.2.1
  - piwik: 0.7.0
  - polls: 1.6.2
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - ransomware_detection: 0.10.0
  - ransomware_protection: 1.8.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - socialsharing_email: 2.1.0
  - spreed: 10.0.4
  - support: 1.3.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - terms_of_service: 1.6.1
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_admin: 3.0.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.1.0
  - twofactor_totp: 5.0.0
  - unsplash: 1.1.7
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - audioplayer
  - camerarawpreviews
  - dashboard
  - dicomviewer
  - encryption
  - files_accesscontrol
  - files_antivirus
  - maps
  - shorten
  - survey_client
  - user_ldap

**Nextcloud configuration:**

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 82

**Operating system:** Mac

#### Nextcloud log (data/owncloud.log)
{"reqId":"X@odmiV4uDgAADBTzBUAAAAH","level":1,"time":"2020-12-28T18:02:03+00:00","remoteAddr":"<ipv6addr>","user":"<username>","app":"no app in context","method":"GET","url":"/ocs/v2.php/core/navigation/apps?absolute=true&format=json","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"ransomwaredetection.page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"<nextcloud_docroot>/lib/private/Route/Router.php","line":370,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"<nextcloud_docroot>/lib/private/Route/CachingRouter.php","line":60,"function":"generate","class":"OC\\Route\\Router","type":"->"},{"file":"<nextcloud_docroot>/lib/private/URLGenerator.php","line":83,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->"},{"file":"<nextcloud_docroot>/lib/private/NavigationManager.php","line":282,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->"},{"file":"<nextcloud_docroot>/lib/private/NavigationManager.php","line":108,"function":"init","class":"OC\\NavigationManager","type":"->"},{"file":"<nextcloud_docroot>/core/Controller/NavigationController.php","line":56,"function":"getAll","class":"OC\\NavigationManager","type":"->"},{"file":"<nextcloud_docroot>/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getAppsNavigation","class":"OC\\Core\\Controller\\NavigationController","type":"->"},{"file":"<nextcloud_docroot>/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"<nextcloud_docroot>/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"<nextcloud_docroot>/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"<nextcloud_docroot>/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"<nextcloud_docroot>/ocs/v2.php","line":24,"args":["<nextcloud_docroot>/ocs/v1.php"],"function":"require_once"}],"File":"<nextcloud_docroot>/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":143,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/3.0.3stable-Win64 (build 20201125) (Nextcloud)","version":"20.0.4.0","id":"<id>"}

**Comment by nickvergessen** [comment]
That's the wrong app(ransomware detection vs. Ransomware protection). Please report at https://github.com/undo-ransomware/ransomware_detection/issues
