### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by sunjam** [nextcloud/ransomware_protection#84]
Related to #83 php8 was introduced in v21.  Note 7.x will continue to be supported for now.

**Comment by nickvergessen** [comment]
This app is not limiting the php version so it will come automatically

**Comment by Aceriz** [comment]
> This app is not limiting the php version so it will come automatically


Just to check sorry still very new to this all.   Does this mean we can install the ransomwear protect or do we have to wait?
