### ISSUE TITLE
Follow-up question re Nextcloud 21

### ISSUE THREAD

**Issue by Aceriz** [nextcloud/ransomware_protection#85]
Hi, 

In advance thank you for response.   I am just wanting to clarify something regarding your response 

"This app is not limiting the php version so it will come automatically"

Thought it was appropriate to make a  new post as I realized the other one was actually closed... (sorry) for double post..

With the PHP version being different.. does this impact my ability to install this ransomware protection app? 

Thank again

**Comment by nickvergessen** [comment]
I'm not sure what your question is. There is a version which works with Nextcloud 18, 19 and 20 and there will be one that works with Nextcloud 21 (independent from any php version and database you run)
