### ISSUE TITLE
New errors with addition of ransomware protection

### ISSUE THREAD

**Issue by Aceriz** [nextcloud/ransomware_protection#88]
Hoping you might be able to help me out.    Thank you so much for updated the app to Nextcloud 21 !!. 
Unfortunately after I disable and removed the old app then restarted the nextcloud docker,  and now reinstalled and enabled this app .  Updating the include lists based on the "resources folder"    I am getting the two below errors on repeat.. every few seconds 

Not sure what to do to assess..

{"reqId":"MTxiAMraajXQ8KWpfa5C","level":3,"time":"2021-03-02T05:39:54+00:00","remoteAddr":"XXX?.XXX.XX.XXX","user"mynextcloud:"mynextcloud","app":"PHP","method":"GET","url":"/ocs/v2.php/search/providers/settings/search?term=ransom&from=%2Fsettings%2Fapps","message":{"Exception":"Error","Message":"include(): Failed opening 'ransomware_protection/personal.php' for inclusion (include_path='/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Crypt_Blowfish:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Date:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Exception:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Idna:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_ListHeaders:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Nls:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Secret:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Socket_Client:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Filter:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Wrapper:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Support:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Filter:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Flowed:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Translation:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Util:/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www/nextcloud/3rdparty/pear/console_getopt:/config/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/config/www/nextcloud/3rdparty/pear/pear_exception:/config/www/nextcloud/apps') at /config/www/nextcloud/lib/private/legacy/OC_App.php#660","Code":0,"Trace":[{"file":"/config/www/nextcloud/lib/private/legacy/OC_App.php","line":660,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/private/legacy/OC_App.php","line":660,"function":"include"},{"file":"/config/www/nextcloud/lib/private/Settings/Manager.php","line":258,"function":"getForms","class":"OC_App","type":"::"},{"file":"/config/www/nextcloud/apps/settings/lib/Search/SectionSearch.php","line":99,"function":"getPersonalSections","class":"OC\\Settings\\Manager","type":"->"},{"file":"/config/www/nextcloud/lib/private/Search/SearchComposer.php","line":162,"function":"search","class":"OCA\\Settings\\Search\\SectionSearch","type":"->"},{"file":"/config/www/nextcloud/core/Controller/UnifiedSearchController.php","line":110,"function":"search","class":"OC\\Search\\SearchComposer","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"search","class":"OC\\Core\\Controller\\UnifiedSearchController","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/config/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/config/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/config/www/nextcloud/ocs/v2.php","line":24,"args":["/config/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36","version":"21.0.0.18","id":"603dcfc106e67"}

second error

{"reqId":"MTxiAMraajXQ8KWpfa5C","level":3,"time":"2021-03-02T05:39:54+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":mynextcloud"","app":"PHP","method":"GET","url":"/ocs/v2.php/search/providers/settings/search?term=ransom&from=%2Fsettings%2Fapps","message":{"Exception":"Error","Message":"include(ransomware_protection/personal.php): failed to open stream: No such file or directory at /config/www/nextcloud/lib/private/legacy/OC_App.php#660","Code":0,"Trace":[{"file":"/config/www/nextcloud/lib/private/legacy/OC_App.php","line":660,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/private/legacy/OC_App.php","line":660,"function":"include"},{"file":"/config/www/nextcloud/lib/private/Settings/Manager.php","line":258,"function":"getForms","class":"OC_App","type":"::"},{"file":"/config/www/nextcloud/apps/settings/lib/Search/SectionSearch.php","line":99,"function":"getPersonalSections","class":"OC\\Settings\\Manager","type":"->"},{"file":"/config/www/nextcloud/lib/private/Search/SearchComposer.php","line":162,"function":"search","class":"OCA\\Settings\\Search\\SectionSearch","type":"->"},{"file":"/config/www/nextcloud/core/Controller/UnifiedSearchController.php","line":110,"function":"search","class":"OC\\Search\\SearchComposer","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"search","class":"OC\\Core\\Controller\\UnifiedSearchController","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/config/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/config/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/config/www/nextcloud/ocs/v2.php","line":24,"args":["/config/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36","version":"21.0.0.18","id":"603dcfc106fbc"}

I am running the linuxserver version of  nextcloud docker on Unraid system 6.8.3    With setup cloudflare and SWAG for reverse proxy
Happy to provide additional information to help figure this out :)

**Comment by nickvergessen** [comment]
So first of all you don't need to update a list based on the resources folder, that is taken into account automatically.
And the errors you see indicates that not allow files were updated correctly

**Comment by Aceriz** [comment]
> So first of all you don't need to update a list based on the resources folder, that is taken into account automatically.
> And the errors you see indicates that not allow files were updated correctly



Thank you for letting me know about not needing to update the resources fields in nextcloud .. I have removed this... 

when you say that it is updating correctly   I am wondering  why it comes up with the errors on repeat like every minute...

Error: include(ransomware_protection/personal.php): failed to open stream: No such file or directory at /config/www/nextcloud/lib/private/legacy/OC_App.php#66

Error: include(): Failed opening 'ransomware_protection/personal.php' for inclusion (include_path='/config/www/nextcloud/apps/mail/vendor/pear-
--




Error: include(): Failed opening 'ransomware_protection/personal.php' for inclusion (include_path='/config/www/nextcloud/apps/mail/vendor/pear-
--

**Comment by nickvergessen** [comment]
The thing is that file is not there and not needed anymore in Nextcloud 21. It was used until 19 only. Since then the code was removed and changed. So you seem to have some old files or caching in place still referencing it.

**Comment by Aceriz** [comment]
> The thing is that file is not there and not needed anymore in Nextcloud 21. It was used until 19 only. Since then the code was removed and changed. So you seem to have some old files or caching in place still referencing it.

Do you know how I might go about removing this ?    would it be just going into the   "appdata\nextcloud\www\nextcloud\apps\mail\vendor"   and removing it?    or does this require other removal ..  

(I had recently ie over the weekend re-done the entire reinstall of nextcloud within my unraid setup.(deleting the appdata data folders)... not sure where to go next...

**Comment by nickvergessen** [comment]
No, the problem is not the mail app code.
There is something strange in your docker.
Please ask the docker devs for help

**Comment by stavros-k** [comment]
i'm having the same issue, 
removed the app completely and reinstalled. still having simillar error.

```

Error: include(): Failed opening 'ransomware_protection/personal.php' for inclusion (include_path='/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Crypt_Blowfish:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Date:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Exception:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Idna:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_ListHeaders:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mail:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Mime:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Nls:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Secret:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Socket_Client:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Filter:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Wrapper:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Support:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Filter:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Flowed:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Translation:/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Util:/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www/nextcloud/3rdparty/pear/console_getopt:/config/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/config/www/nextcloud/3rdparty/pear/pear_exception:/config/www/nextcloud/apps') at /config/www/nextcloud/lib/private/legacy/OC_App.php#660/config/www/nextcloud/lib/private/legacy/OC_App.php - line 660:OC\Log\ErrorHandler::onError()/config/www/nextcloud/lib/private/legacy/OC_App.php - line 660:include()/config/www/nextcloud/lib/private/Settings/Manager.php - line 258:OC_App::getForms()/config/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 116:OC\Settings\Manager->getPersonalSections()/config/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 64:OCA\Settings\Controller\AdminSettingsController->formatPersonalSections()/config/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 148:OCA\Settings\Controller\AdminSettingsController->getNavigationParameters()/config/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php - line 68:OCA\Settings\Controller\AdminSettingsController->getIndexResponse()/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:OCA\Settings\Controller\AdminSettingsController->index()/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:OC\AppFramework\Http\Dispatcher->executeController()/config/www/nextcloud/lib/private/AppFramework/App.php - line 157:OC\AppFramework\Http\Dispatcher->dispatch()/config/www/nextcloud/lib/private/Route/Router.php - line 302:OC\AppFramework\App::main()/config/www/nextcloud/lib/base.php - line 993:OC\Route\Router->match()/config/www/nextcloud/index.php - line 37:OC::handleRequest()
--

```

**Comment by nickvergessen** [comment]
Please test the following patch https://github.com/nextcloud/ransomware_protection/pull/90/files

**Comment by Aceriz** [comment]
> Please test the following patch https://github.com/nextcloud/ransomware_protection/pull/90/files

I am happy to give this a test tonight.   Could you explain how I would go about this within unraid install of nextcloud ?  just want to ensure I am doing it correctly for the test  

ie where should I put this ?

**Comment by Schmuuu** [comment]
> Please test the following patch https://github.com/nextcloud/ransomware_protection/pull/90/files

That solved it for me. Thank you @nickvergessen
