### ISSUE TITLE
Personal.php

### ISSUE THREAD

**Issue by derritter88** [nextcloud/ransomware_protection#94]
With regards to #93 : After the upgrade to ransomware protection v1.10.0 I still see the issue within my Nextcloud log

**Comment by derritter88** [comment]
Probably a cache issue on my side - restarted php7.4-fpm.
Will keep an eye on it and close the issue if that solved the issue.

**Comment by nickvergessen** [comment]
Otherwise please post a full log line

**Comment by derritter88** [comment]
Seems to be a cache related thing.
After I restarted the services and cleared the cache no further log entries can be found.

If this issue will appear again I'll log a new issue including log output.
