### ISSUE TITLE
.aac audio file is not kept on server -

### ISSUE THREAD

**Issue by e-yonder** [nextcloud/ransomware_protection#96]
Hello,
I am using Nextcloud 21.01, on ubuntu 20.04.1, php7.4.3, php-fpm enabled, mariadb-mysql 10.3.25.
The browser I have used is Firefox 87.0 64 bits.

I have been setting up different folders to be synchronized.
I have one **.aac audio file** which won't be kept on the server (as per the error message that is displayed by the nextcloud windows client). It keeps trying to synchronize this file on a loop to no avail, and to make this file stay on the server.

I have briefly disabled 'ransmware protectection', and this loop stopped. I have then re-enabled 'ransomware protection'. The error message appearing on a loop has not reappeared.

Regards,
Christophe

**Comment by nursoda** [comment]
.aac is an extension that is used by some ransomware encryptors, so it's one line in the file apps/ransomware_protection/resources/extensions.txt that you may or may not access via shell access. To disable this extension from being blocked, please just add ".aac" to the corresponding ransomware protection configuration box in the web interface in https://cloud.SERVER.TLD/settings/admin/security. Works for me like that on a similar setup.

**Comment by nightthinker22** [comment]
> `.aac` is an extension that is used by some ransomware encryptors, so it's one line in the file `apps/ransomware_protection/resources/extensions.txt` that you may or may not access via shell access. To disable this extension from being blocked, please just add ".aac" to the corresponding ransomware protection configuration box in the web interface in `https://cloud.SERVER.TLD/settings/admin/security`. Works for me like that on a similar setup.

- Mll
